### ISSUE TITLE
bucketing algorithm appears to return the same allocation across variationGroups

### ISSUE THREAD

**Issue by chrskrchr** [abtasty/flagship-go-sdk#3]
Hi,
Quick question about the `GetRandomAllocation` hashing function:

https://github.com/abtasty/flagship-go-sdk/blob/master/pkg/bucketing/allocation.go#L11-L33

It appears to include the visitor ID and nothing else when generating the murmur3 hash.  Doesn't this mean that a visitor ID will end up in the same variant across any `VariationGroup`s with similar definitions?  For example, say you have 10 flags that all use a 50/50 split.  Based on the current `GetRandomAllocation` implementation, doesn't that mean that a visitor ID is going to get hashed into either all of the control buckets or all of the variant buckets across those flags?

**Comment by chrskrchr** [comment]
FWIW - it appears the same behavior exists in the Node SDK:

https://github.com/abtasty/flagship-js-sdk/blob/30429a95e3250877856e17858b549758ca083fe9/src/class/bucketingVisitor/bucketingVisitor.ts#L80

**Comment by guillaumejacquart** [comment]
Hey Chris,
Thanks for your feedback.
Indeed you're totally right, we noticed this issue some time ago, but waited on all SDK to align to adding the variation group ID in the hash.
We will release that fix tomorrow morning for all SDKs

**Comment by chrskrchr** [comment]
Thanks for the quick response!  That's great news that a fix is on the way.  

Can you confirm that bucketing results are expected to be the consistent for the same `VariantGroup + VisitorID` across SDKs?  This looks to be the case given the similar hashing algorithms implemented in the SDKs, but I couldn't find any mention of that feature in the [Flagship docs](https://developers.flagship.io/).  Related question - will we get the same bucketing answer when calling the remote Flagship Decision API?  (assuming it's using the same hashing algorithm on your backend?)

Last question - how do you plan on releasing this fix in the client SDKs?  Would we just need to bump our client SDK version?

I'm curious because if it's just a simple client SDK upgrade, then a progressive rollout of the new client SDKs could potentially break the "consistent bucketing across SDKs" requirement just discussed as some apps upgrade to the newer SDK and others don't.  To be honest, this is just a hypothetical question for us at this point since we haven't yet adopted Flagship on the backend.  I'm mainly just curious so we can understand how we'll need to deal with breaking changes like this in the future.

**Comment by guillaumejacquart** [comment]
Hey again!
You're absolutely right, visitor assignment will potentially be changed if you update the SDK (once the release - with a new version-) will be up. We would advice to upgrade the SDK when no campaigns is still running and before launching new ones if possible.  
Hopefully breaking changes like that in the visitor assignment won't be frequent. 
We are also working on a document page regarding bucketing rules and consistency across SDK / Decision API. 
Thanks for your relevant remarks anyway ;) we appreciate it.

**Comment by chrskrchr** [comment]
OK - thanks!

**Comment by guillaumejacquart** [comment]
Fixed since v2 (https://github.com/abtasty/flagship-go-sdk/releases/tag/v2.0.0).
We had issues with the new major version release.
