### ISSUE TITLE
Unsafe re-use of murmur3.New32() variable

### ISSUE THREAD

**Issue by pkwarren** [abtasty/flagship-go-sdk#4]
https://github.com/abtasty/flagship-go-sdk/blob/ada5729f682fa434b3dc3ac08dc5f7b7087c9721/pkg/bucketing/allocation.go#L9

This doesn't appear to be safe for use if GetRandomAllocation is called across goroutines. I'd recommend either just allocating a new hash in GetRandomAllocation each time or using something like sync.Pool() if critical for performance.

**Comment by guillaumejacquart** [comment]
Hey Philip,
You're totally right, nice catch. A PR is in review #11 and will soon be merged

**Comment by pkwarren** [comment]
Fixed as part of #11.
