### ISSUE TITLE
Failures when building tests with race detection

### ISSUE THREAD

**Issue by pkwarren** [abtasty/flagship-go-sdk#5]
I saw some unsafe concurrent access patterns in the bucketing client and running tests with `go test -v ./... -race` showed that there were race conditions. I'd recommend making the following changes:

1. Use a pointer receiver `r *APIClient` here: https://github.com/abtasty/flagship-go-sdk/blob/ada5729f682fa434b3dc3ac08dc5f7b7087c9721/pkg/bucketing/api_client.go#L86
1. Use a pointer receiver `r *APIClientMock` here: https://github.com/abtasty/flagship-go-sdk/blob/ada5729f682fa434b3dc3ac08dc5f7b7087c9721/pkg/bucketing/api_client_mock.go#L22
1. Use a lock to protect assignment of apiClient (as it is used by a background goroutine) here: https://github.com/abtasty/flagship-go-sdk/blob/ada5729f682fa434b3dc3ac08dc5f7b7087c9721/pkg/bucketing/engine.go#L54 and here: https://github.com/abtasty/flagship-go-sdk/blob/ada5729f682fa434b3dc3ac08dc5f7b7087c9721/pkg/bucketing/engine_test.go#L160
1. Use a lock to protect read of apiClient here: https://github.com/abtasty/flagship-go-sdk/blob/ada5729f682fa434b3dc3ac08dc5f7b7087c9721/pkg/bucketing/engine.go#L84
1. In `GetModifications`, all access to `b.config` should be protected by a lock (might want to consider making the `configMux` be a `sync.RWLock`). I'd recommend assigning a variable to the current config at the beginning and using it throughout.
1. In engine_test.go, replace all calls to `engine.config` to a method which uses a lock (i.e. `getConfig()`) to return a consistent version.

With these changes, I'm able to get tests to run with the race detector locally.

**Comment by guillaumejacquart** [comment]
Hey Philip,
Thanks for this relevant remark. I made a pull request for this race condition optimization : #8 
It will soon be merged on master and deployed as a new version (probably with other fixes you mentioned)

**Comment by pkwarren** [comment]
Fixed as part of #8.
