### ISSUE TITLE
Unhandled error in cache local Set() method

### ISSUE THREAD

**Issue by pkwarren** [abtasty/flagship-go-sdk#6]
https://github.com/abtasty/flagship-go-sdk/blob/ada5729f682fa434b3dc3ac08dc5f7b7087c9721/pkg/cache/local.go#L50

This looks like it needs to return the error from the call to Put() here.

**Comment by guillaumejacquart** [comment]
Hey Philip,
Thanks, a bunch of fixes and error checking will be added soon (see PR #9 )

**Comment by guillaumejacquart** [comment]
Fixed in new version (https://github.com/abtasty/flagship-go-sdk/releases/tag/v2.0.2)
